image:
    name: debian:testing

services:
    - docker:19.03.12-dind

stages:
    - build
    - test
    - deploy

build:
    stage: build
    before_script:
        - apt -y update
        - apt -y install git cmake gcc g++
        - apt -y install libcurl4 libssl1.1
        - apt -y install libcurl4-openssl-dev libssl-dev
    script:
        - cmake -S. -Bbuild
        - cmake --build build
    artifacts:
        paths:
            - build/

test:
    stage: test
    before_script:
        - apt -y update
        - apt -y install libcurl4 libssl1.1
    script:
        - build/src/test/unittests
    artifacts:
        paths:
            - build/

deploy:
    stage: deploy
    script:
        - echo deploy
    only:
        - master
