workflow:
    rules:
        - if: $CI_COMMIT_TAG
        - if: $CI_COMMIT_BRANCH
        - if: $CI_MERGE_REQUEST_IID

image:
    name: debian:stable

services:
    - docker:18-dind

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - build

stages:
    - build
    - test
    - deploy

build-debian:
    image: debian:stable
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    stage: build
    before_script:
        - apt -y update
        - apt -y install cmake gcc g++
        - apt -y install libcurl4-openssl-dev libssl-dev
        - apt -y install dpkg-dev file
    script:
        - cmake -S. -Bbuild
        - cmake --build build -- -j$(nproc)
        - cmake --build build --target package -- -j$(nproc)

build-centos:
    image: centos:8
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    stage: build
    before_script:
        - yum -y update
        - yum install -y gcc gcc-c++ make gmp-c++ gmp-devel 
        - yum install -y openssl-devel libcurl-devel file rpm-build cmake
    script:
        - cmake -S. -Bbuild
        - cmake --build build -- -j$(nproc)
        - cmake --build build --target package -- -j$(nproc)

test-debian:
    image: debian:stable
    stage: test
    before_script:
        - apt -y update
        - apt -y install libcurl4 libssl1.1
    script:
        - build/src/test/unittests

test-centos:
    image: centos:8
    stage: test
    before_script:
        - yum -y update
    script:
        - build/src/test/unittests

deploy:
    image: debian:stable
    stage: deploy
    before_script:
        - apt -y update
        - apt -y install docker.io
        - docker login --username ${DOCKERHUB_USER} --password-stdin < ${DOCKERHUB_TOKEN}
    script:
        - docker build -t ubiqsecurity/ubiq-c-cpp-sample -f src/examples/Dockerfile .
        - docker tag ubiqsecurity/ubiq-c-cpp-sample ubiqsecurity/ubiq-c-cpp-sample:${CI_COMMIT_TAG:-latest}
        - docker push ubiqsecurity/ubiq-c-cpp-sample
    after_script:
        - docker logout
    artifacts:
        # gitlab will keep the most recent artifacts
        # regardless of the expiration time
        expire_in: 1 hour
        paths:
            - build/*.deb
    only:
        - master
        - tags
    except:
        - schedules
