image:
    name: debian:testing

services:
    - docker:19.03.12-dind

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - echo build

test:
    stage: test
    script:
        - echo test

deploy:
    stage: deploy
    script:
        - echo deploy
    only:
        - master
